version: 2.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/repo/node_modules
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
          
workflows:
  build-and-test:
    jobs:
      - build
